### ISSUE TITLE
Password Page

### ISSUE THREAD

**Issue by TomaszSzelachowski** [fccc0239b79/PChecker#1]
When you type in username or password it cuts out some of the writting

**Comment by TomaszSzelachowski** [comment]
not sure if this is a issue or just my pc

**Comment by gregl33** [comment]
fixed, increased the width of both input fields so no text is cut off

**Comment by TomaszSzelachowski** [comment]
Not fixed, as depends on resolution of screen, so this can still be an issue

**Comment by gregl33** [comment]
fixed
